// get topics
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_ERROR = 'GET_TOPICS_ERROR';

// get single topics
export const GET_SINGLE_TOPIC_REQUEST = 'GET_SINGLE_TOPIC_REQUEST';
export const GET_SINGLE_TOPIC_SUCCESS = 'GET_SINGLE_TOPIC_SUCCESS';
export const GET_SINGLE_TOPIC_ERROR = 'GET_SINGLE_TOPIC_ERROR';

// get comments
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

// get replies
export const GET_REPLIES_REQUEST = 'GET_REPLIES_REQUEST';
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESSS';
export const GET_REPLIES_ERROR = 'GET_REPLIES_ERROR';
